language: php

addons:
  mariadb: '10.0'

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  - DB=mysql

before_script:
  - mysql -e "INSTALL PLUGIN handlersocket SONAME 'handlersocket.so';"
  - ./travis/configure_restart_mariadb.sh
  - mysql -e "SHOW PROCESSLIST;"
  - mysql -e 'CREATE DATABASE IF NOT EXISTS HSPHP_test;'
  - mysql -D HSPHP_test < tests/HSPHP/import.sql
  - composer self-update
  - composer install

script: phpunit
